stages:
  - build

variables:
  APP_NAME: uw-mydb-mysql
  APP_VERSION: 8.4.0
  REGISTRY: "dev.xili.pub:5000"

# 编译
build:
  stage: build
  only:
    - main
    - master
  script:
    - docker build -t ${REGISTRY}/${APP_NAME}:${APP_VERSION} .
    - docker push ${REGISTRY}/${APP_NAME}:${APP_VERSION}
    #- /home/gitlab-runner/bin/deploy-registry-app.sh ${REGISTRY} ${APP_NAME} ${APP_VERSION} ${APP_PORT} ${APP_MEM}
